import type { TasteDnaResponse } from '../api/types'
import { GlassPanel } from './GlassPanel'

type Props = {
  tasteDna: TasteDnaResponse
}

export function TasteView({ tasteDna }: Props) {
  const { content } = tasteDna

  return (
    <div className="reveal h-full overflow-auto pr-1">
      <GlassPanel strong className="p-8">
        <p className="text-[10px] font-semibold tracking-[0.18em] text-[var(--color-accent)] uppercase">
          Taste DNA
        </p>
        <h2 className="font-display mt-3 text-4xl font-extrabold tracking-tight">
          {content.headline || 'Living profile'}
        </h2>
        <p className="mt-5 max-w-3xl text-base leading-relaxed text-[var(--color-muted)]">
          {content.summary || 'No Taste DNA narrative generated yet.'}
        </p>

        <div className="mt-10 grid gap-8 md:grid-cols-3">
          <ListBlock title="Core genres" items={content.core_genres ?? []} />
          <ListBlock title="Core artists" items={content.core_artists ?? []} />
          <ListBlock title="Major shift months" items={content.major_shift_months ?? []} />
        </div>

        {tasteDna.model ? (
          <p className="mt-10 text-xs text-[var(--color-muted)]">
            Generated by {tasteDna.model}
            {tasteDna.generated_at ? ` · ${tasteDna.generated_at}` : ''}
          </p>
        ) : null}
      </GlassPanel>
    </div>
  )
}

function ListBlock({ title, items }: { title: string; items: string[] }) {
  return (
    <div>
      <h3 className="text-[10px] font-semibold tracking-[0.16em] text-[var(--color-warm)] uppercase">
        {title}
      </h3>
      {items.length === 0 ? (
        <p className="mt-3 text-sm text-[var(--color-muted)]">None recorded</p>
      ) : (
        <ul className="mt-3 space-y-2">
          {items.map((item) => (
            <li
              key={item}
              className="rounded-xl border border-[var(--color-line)] bg-white/5 px-3 py-2 text-sm font-medium"
            >
              {item}
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}
